title: "MPSAT-ETP"
lang: fr
language:
  title-block-author-single: "Auteur"
author:
  - name: "D<up>r</up> Philippe MICHEL"
    affiliations:
      name: "USRC - Hôpital NOVO"
      department: "Unité de Soutien à la Recherche Clinique"
format:
  html:
    theme: minty
    code-fold: true
    html-math-method: katex
    highlight-style: ayu
    page-layout: full
    toc: true
    number-sections: true
    smooth-scroll: true
bibliography: stat.bib
license: "MIT"
warning: false
message: false
cache: true
